

import 'package:easy_localization/easy_localization.dart';
import 'package:islamic_tools_app/models/quran_list_model.dart';

final List<String> quranListNames = [
  "quran.surah1".tr(),
  "quran.surah2".tr(),
  "quran.surah3".tr(),
  "quran.surah4".tr(),
  "quran.surah5".tr(),
  "quran.surah6".tr(),
  "quran.surah7".tr(),
  "quran.surah8".tr(),
  "quran.surah9".tr(),
  "quran.surah10".tr(),
  "quran.surah11".tr(),
  "quran.surah12".tr(),
  "quran.surah13".tr(),
  "quran.surah14".tr(),
  "quran.surah15".tr(),
  "quran.surah16".tr(),
  "quran.surah17".tr(),
  "quran.surah18".tr(),
  "quran.surah19".tr(),
  "quran.surah20".tr(),
  "quran.surah21".tr(),
  "quran.surah22".tr(),
  "quran.surah23".tr(),
  "quran.surah24".tr(),
  "quran.surah25".tr(),
  "quran.surah26".tr(),
  "quran.surah27".tr(),
  "quran.surah28".tr(),
  "quran.surah29".tr(),
  "quran.surah30".tr(),
  "quran.surah31".tr(),
  "quran.surah32".tr(),
  "quran.surah33".tr(),
  "quran.surah34".tr(),
  "quran.surah35".tr(),
  "quran.surah36".tr(),
  "quran.surah37".tr(),
  "quran.surah38".tr(),
  "quran.surah39".tr(),
  "quran.surah40".tr(),
  "quran.surah41".tr(),
  "quran.surah42".tr(),
  "quran.surah43".tr(),
  "quran.surah44".tr(),
  "quran.surah45".tr(),
  "quran.surah46".tr(),
  "quran.surah47".tr(),
  "quran.surah48".tr(),
  "quran.surah49".tr(),
  "quran.surah50".tr(),
  "quran.surah51".tr(),
  "quran.surah52".tr(),
  "quran.surah53".tr(),
  "quran.surah54".tr(),
  "quran.surah55".tr(),
  "quran.surah56".tr(),
  "quran.surah57".tr(),
  "quran.surah58".tr(),
  "quran.surah59".tr(),
  "quran.surah60".tr(),
  "quran.surah61".tr(),
  "quran.surah62".tr(),
  "quran.surah63".tr(),
  "quran.surah64".tr(),
  "quran.surah65".tr(),
  "quran.surah66".tr(),
  "quran.surah67".tr(),
  "quran.surah68".tr(),
  "quran.surah69".tr(),
  "quran.surah70".tr(),
  "quran.surah71".tr(),
  "quran.surah72".tr(),
  "quran.surah73".tr(),
  "quran.surah74".tr(),
  "quran.surah75".tr(),
  "quran.surah76".tr(),
  "quran.surah77".tr(),
  "quran.surah78".tr(),
  "quran.surah79".tr(),
  "quran.surah80".tr(),
  "quran.surah81".tr(),
  "quran.surah82".tr(),
  "quran.surah83".tr(),
  "quran.surah84".tr(),
  "quran.surah85".tr(),
  "quran.surah86".tr(),
  "quran.surah87".tr(),
  "quran.surah88".tr(),
  "quran.surah89".tr(),
  "quran.surah90".tr(),
  "quran.surah91".tr(),
  "quran.surah92".tr(),
  "quran.surah93".tr(),
  "quran.surah94".tr(),
  "quran.surah95".tr(),
  "quran.surah96".tr(),
  "quran.surah97".tr(),
  "quran.surah98".tr(),
  "quran.surah99".tr(),
  "quran.surah100".tr(),
  "quran.surah101".tr(),
  "quran.surah102".tr(),
  "quran.surah103".tr(),
  "quran.surah104".tr(),
  "quran.surah105".tr(),
  "quran.surah106".tr(),
  "quran.surah107".tr(),
  "quran.surah108".tr(),
  "quran.surah109".tr(),
  "quran.surah110".tr(),
  "quran.surah111".tr(),
  "quran.surah112".tr(),
  "quran.surah113".tr(),
  "quran.surah114".tr(),
];


// Convert to list of objects using map with index
final List<QuranListModel> quranChapters = quranListNames
    .asMap()
    .entries
    .map((entry) => QuranListModel(
  quranListName: entry.value,
  //add 1 because index starts from 0
  quranListNumber: entry.key + 1, // Now in Arabic
))
.toList();